using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DingoGameObjectsCMS.RuntimeObjects.DotsState;

namespace DingoGameObjectsCMS.Editor
{
    public class RuntimeDotsStateCodeEmissionProfile
    {
        public readonly string GeneratedNamespace;
        public readonly string RegistryClassName;

        public RuntimeDotsStateCodeEmissionProfile(
            string generatedNamespace,
            string registryClassName)
        {
            if (string.IsNullOrWhiteSpace(generatedNamespace))
            {
                throw new ArgumentException(
                    "Generated DOTS state namespace is required.",
                    nameof(generatedNamespace));
            }
            if (string.IsNullOrWhiteSpace(registryClassName))
            {
                throw new ArgumentException(
                    "Generated DOTS state registry class name is required.",
                    nameof(registryClassName));
            }

            GeneratedNamespace = generatedNamespace.Trim();
            RegistryClassName = registryClassName.Trim();
        }
    }

    public static class RuntimeDotsStateCodeEmitter
    {
        public static string Generate(
            RuntimeDotsStateSchemaManifest manifest,
            IReadOnlyList<RuntimeDotsStateGeneratedComponentDescriptor>
                descriptors,
            RuntimeDotsStateCodeEmissionProfile profile)
        {
            if (manifest == null)
            {
                throw new ArgumentNullException(nameof(manifest));
            }
            if (descriptors == null)
            {
                throw new ArgumentNullException(nameof(descriptors));
            }
            if (profile == null)
            {
                throw new ArgumentNullException(nameof(profile));
            }
            if (string.IsNullOrWhiteSpace(manifest.SchemaHash))
            {
                throw new InvalidOperationException(
                    "Cannot emit a DOTS state registry without a schema hash.");
            }

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />")
                .AppendLine("using System;")
                .AppendLine("using System.Collections.Generic;")
                .AppendLine("using DingoGameObjectsCMS.RuntimeObjects.DotsState;")
                .AppendLine("using DingoGameObjectsCMS.RuntimeObjects.Replay;")
                .AppendLine("using Unity.Entities;")
                .AppendLine("using UnityEngine.Scripting;")
                .AppendLine()
                .Append("namespace ")
                .Append(profile.GeneratedNamespace)
                .AppendLine()
                .AppendLine("{")
                .AppendLine("    [Preserve]")
                .Append("    public static class ")
                .Append(profile.RegistryClassName)
                .AppendLine()
                .AppendLine("    {")
                .Append("        public const string SchemaHash = ")
                .Append(Quote(manifest.SchemaHash))
                .AppendLine(";")
                .AppendLine()
                .AppendLine("        public static RuntimeDotsStateSchemaRegistry CreateSchema()")
                .AppendLine("        {")
                .AppendLine("            var schema = new RuntimeDotsStateSchemaRegistry(SchemaHash);")
                .AppendLine("            Register(schema);")
                .AppendLine("            return schema;")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        public static void Register(RuntimeDotsStateSchemaRegistry schema)")
                .AppendLine("        {")
                .AppendLine("            if (schema == null)")
                .AppendLine("                throw new ArgumentNullException(nameof(schema));")
                .AppendLine("            if (!string.Equals(schema.SchemaHash, SchemaHash, StringComparison.Ordinal))")
                .AppendLine("                throw new InvalidOperationException(\"DOTS state schema hash mismatch.\");");

            foreach (var descriptor in descriptors
                         .Where(value => value?.Schema != null)
                         .OrderBy(value => value.Schema.ComponentTypeId))
            {
                var schema = descriptor.Schema;
                var descriptorName =
                    $"descriptor{schema.ComponentTypeId}";
                builder.AppendLine()
                    .Append("            var ")
                    .Append(descriptorName)
                    .Append(" = RuntimeDotsStateComponentDescriptor.")
                    .Append(schema.Kind == RuntimeDotsStateComponentKind.Buffer
                        ? "Buffer<"
                        : "Component<")
                    .Append(TypeName(descriptor.RuntimeType))
                    .AppendLine(">(")
                    .Append("                ")
                    .Append(schema.ComponentTypeId)
                    .AppendLine(",")
                    .Append("                RuntimeDotsStateClassification.")
                    .Append(schema.Classification)
                    .AppendLine(",")
                    .Append("                ")
                    .Append(schema.Enableable ? "true" : "false")
                    .AppendLine(");")
                    .Append("            schema.Register(")
                    .Append(descriptorName);
                if (schema.Classification ==
                    RuntimeDotsStateClassification.Persisted)
                {
                    builder.Append(", Codec_")
                        .Append(schema.ComponentTypeId);
                }
                builder.AppendLine(");");
            }

            builder.AppendLine("        }");
            EmitEntityRowMethods(builder, descriptors);
            foreach (var descriptor in descriptors
                         .Where(value => value?.Schema != null
                                         && value.Schema.Classification ==
                                         RuntimeDotsStateClassification.Persisted)
                         .OrderBy(value => value.Schema.ComponentTypeId))
            {
                EmitPersistedCodec(builder, descriptor);
            }

            EmitCreateManifest(builder, manifest);
            builder.AppendLine("    }")
                .AppendLine("}");
            return builder.ToString();
        }

        private static void EmitCreateManifest(
            StringBuilder builder,
            RuntimeDotsStateSchemaManifest manifest)
        {
            builder.AppendLine()
                .AppendLine("        public static RuntimeDotsStateSchemaManifest CreateManifest()")
                .AppendLine("        {")
                .AppendLine("            return new RuntimeDotsStateSchemaManifest")
                .AppendLine("            {")
                .Append("                FormatVersion = ")
                .Append(manifest.FormatVersion)
                .AppendLine(",")
                .Append("                CodecVersion = ")
                .Append(manifest.CodecVersion)
                .AppendLine(",")
                .Append("                SchemaHash = ")
                .Append(Quote(manifest.SchemaHash))
                .AppendLine(",")
                .AppendLine("                Components = new List<RuntimeDotsStateComponentSchema>")
                .AppendLine("                {");

            foreach (var component in manifest.Components
                         .Where(value => value != null)
                         .OrderBy(value => value.ComponentTypeId))
            {
                if (component.RuntimeType == null)
                {
                    throw new InvalidOperationException(
                        $"Active DOTS state component id {component.ComponentTypeId} requires RuntimeType = typeof(T).");
                }
                builder.AppendLine("                    new RuntimeDotsStateComponentSchema")
                    .AppendLine("                    {")
                    .Append("                        ComponentTypeId = ")
                    .Append(component.ComponentTypeId)
                    .AppendLine(",")
                    .Append("                        RuntimeType = typeof(")
                    .Append(TypeName(component.RuntimeType))
                    .AppendLine("),")
                    .Append("                        Classification = RuntimeDotsStateClassification.")
                    .Append(component.Classification)
                    .AppendLine(",")
                    .Append("                        Kind = RuntimeDotsStateComponentKind.")
                    .Append(component.Kind)
                    .AppendLine(",")
                    .Append("                        Enableable = ")
                    .Append(component.Enableable ? "true" : "false")
                    .AppendLine(",")
                    .Append("                        LayoutHash = ")
                    .Append(component.LayoutHash)
                    .Append("UL")
                    .AppendLine(",")
                    .AppendLine("                    },");
            }

            builder.AppendLine("                },")
                .AppendLine("                ReservedComponentTypeIds = new List<int>")
                .AppendLine("                {");
            foreach (var id in (manifest.ReservedComponentTypeIds
                                ?? new List<int>())
                         .OrderBy(value => value))
            {
                builder.Append("                    ")
                    .Append(id)
                    .AppendLine(",");
            }
            builder.AppendLine("                },")
                .AppendLine("            };")
                .AppendLine("        }");
        }

        private static void EmitEntityRowMethods(
            StringBuilder builder,
            IReadOnlyList<RuntimeDotsStateGeneratedComponentDescriptor>
                descriptors)
        {
            var persisted = descriptors
                .Where(value => value?.Schema != null
                                && value.Schema.Classification ==
                                RuntimeDotsStateClassification.Persisted)
                .OrderBy(value => value.Schema.ComponentTypeId)
                .ToArray();

            builder.AppendLine()
                .AppendLine("        /// <summary>")
                .AppendLine("        /// Cold checkpoint-barrier path only. Writes one entity row in fixed schema order.")
                .AppendLine("        /// </summary>")
                .AppendLine("        public static void WritePersistedEntityState(")
                .AppendLine("            EntityManager entityManager,")
                .AppendLine("            Entity entity,")
                .AppendLine("            RuntimeReplayCheckpointWriter writer)")
                .AppendLine("        {")
                .AppendLine("            if (!entityManager.Exists(entity))")
                .AppendLine("                throw new ArgumentException(\"Cannot write DOTS state for a missing entity.\", nameof(entity));")
                .AppendLine("            if (writer == null)")
                .AppendLine("                throw new ArgumentNullException(nameof(writer));");
            for (var i = 0; i < persisted.Length; i++)
            {
                EmitWriteEntityComponent(builder, persisted[i]);
            }
            builder.AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>")
                .AppendLine("        /// Cold restore prevalidation before factory topology is materialized. Consumes one row without ECS access.")
                .AppendLine("        /// </summary>")
                .AppendLine("        public static void PrevalidatePersistedEntityState(")
                .AppendLine("            RuntimeReplayCheckpointReader reader)")
                .AppendLine("        {")
                .AppendLine("            if (reader == null)")
                .AppendLine("                throw new ArgumentNullException(nameof(reader));");
            for (var i = 0; i < persisted.Length; i++)
            {
                EmitPrevalidateEntityComponent(builder, persisted[i]);
            }
            builder.AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>")
                .AppendLine("        /// Cold restore prevalidation. Consumes one row without mutating the target.")
                .AppendLine("        /// </summary>")
                .AppendLine("        public static void PrevalidatePersistedEntityState(")
                .AppendLine("            EntityManager entityManager,")
                .AppendLine("            Entity entity,")
                .AppendLine("            RuntimeReplayCheckpointReader reader)")
                .AppendLine("        {")
                .AppendLine("            if (!entityManager.Exists(entity))")
                .AppendLine("                throw new ArgumentException(\"Cannot validate DOTS state for a missing entity.\", nameof(entity));")
                .AppendLine("            if (reader == null)")
                .AppendLine("                throw new ArgumentNullException(nameof(reader));");
            for (var i = 0; i < persisted.Length; i++)
            {
                EmitReadEntityComponent(
                    builder,
                    persisted[i],
                    prevalidateOnly: true);
            }
            builder.AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>")
                .AppendLine("        /// Cold checkpoint-barrier path only. Applies one prevalidated entity row.")
                .AppendLine("        /// </summary>")
                .AppendLine("        public static void ReadPersistedEntityState(")
                .AppendLine("            EntityManager entityManager,")
                .AppendLine("            Entity entity,")
                .AppendLine("            RuntimeReplayCheckpointReader reader)")
                .AppendLine("        {")
                .AppendLine("            if (!entityManager.Exists(entity))")
                .AppendLine("                throw new ArgumentException(\"Cannot restore DOTS state for a missing entity.\", nameof(entity));")
                .AppendLine("            if (reader == null)")
                .AppendLine("                throw new ArgumentNullException(nameof(reader));");
            for (var i = 0; i < persisted.Length; i++)
            {
                EmitReadEntityComponent(
                    builder,
                    persisted[i],
                    prevalidateOnly: false);
            }
            builder.AppendLine("        }");
        }

        private static void EmitWriteEntityComponent(
            StringBuilder builder,
            RuntimeDotsStateGeneratedComponentDescriptor descriptor)
        {
            var id = descriptor.Schema.ComponentTypeId;
            var typeName = TypeName(descriptor.RuntimeType);
            var hasMethod = descriptor.Schema.Kind ==
                            RuntimeDotsStateComponentKind.Buffer
                ? "HasBuffer"
                : "HasComponent";
            builder.AppendLine()
                .Append("            var present")
                .Append(id)
                .Append(" = entityManager.")
                .Append(hasMethod)
                .Append('<')
                .Append(typeName)
                .AppendLine(">(entity);")
                .Append("            writer.WriteBoolean(present")
                .Append(id)
                .AppendLine(");")
                .Append("            if (present")
                .Append(id)
                .AppendLine(")")
                .AppendLine("            {");
            if (descriptor.Schema.Enableable)
            {
                builder.Append("                writer.WriteBoolean(entityManager.IsComponentEnabled<")
                    .Append(typeName)
                    .AppendLine(">(entity));");
            }
            if (descriptor.Schema.Kind ==
                RuntimeDotsStateComponentKind.Buffer)
            {
                builder.Append("                var buffer")
                    .Append(id)
                    .Append(" = entityManager.GetBuffer<")
                    .Append(typeName)
                    .AppendLine(">(entity);");
                if (descriptor.PersistedBufferTailValidator != null)
                {
                    builder.Append("                var tail")
                        .Append(id)
                        .Append(" = buffer")
                        .Append(id)
                        .Append(".Length > 0 ? buffer")
                        .Append(id)
                        .Append("[buffer")
                        .Append(id)
                        .AppendLine(".Length - 1] : default;");
                    EmitBufferTailValidation(
                        builder,
                        descriptor,
                        $"buffer{id}.Length",
                        $"tail{id}",
                        "                ",
                        payload: false);
                }
                builder.Append("                writer.WriteInt32(buffer")
                    .Append(id)
                    .AppendLine(".Length);")
                    .Append("                for (var index")
                    .Append(id)
                    .Append(" = 0; index")
                    .Append(id)
                    .Append(" < buffer")
                    .Append(id)
                    .Append(".Length; index")
                    .Append(id)
                    .AppendLine("++)")
                    .AppendLine("                {")
                    .Append("                    var value")
                    .Append(id)
                    .Append(" = buffer")
                    .Append(id)
                    .Append("[index")
                    .Append(id)
                    .AppendLine("];")
                    .Append("                    Write_")
                    .Append(id)
                    .Append("(writer, in value")
                    .Append(id)
                    .AppendLine(");")
                    .AppendLine("                }");
            }
            else if (!descriptor.IsZeroSized)
            {
                builder.Append("                var value")
                    .Append(id)
                    .Append(" = entityManager.GetComponentData<")
                    .Append(typeName)
                    .AppendLine(">(entity);")
                    .Append("                Write_")
                    .Append(id)
                    .Append("(writer, in value")
                    .Append(id)
                    .AppendLine(");");
            }
            builder.AppendLine("            }");
        }

        private static void EmitPrevalidateEntityComponent(
            StringBuilder builder,
            RuntimeDotsStateGeneratedComponentDescriptor descriptor)
        {
            var id = descriptor.Schema.ComponentTypeId;
            builder.AppendLine()
                .Append("            var sourcePresent")
                .Append(id)
                .AppendLine(" = reader.ReadBoolean();")
                .Append("            if (sourcePresent")
                .Append(id)
                .AppendLine(")")
                .AppendLine("            {");
            if (descriptor.Schema.Enableable)
            {
                builder.AppendLine("                _ = reader.ReadBoolean();");
            }
            if (descriptor.Schema.Kind ==
                RuntimeDotsStateComponentKind.Buffer)
            {
                builder.Append("                var count")
                    .Append(id)
                    .AppendLine(" = reader.ReadInt32();")
                    .Append("                if (count")
                    .Append(id)
                    .Append(" < 0 || count")
                    .Append(id)
                    .AppendLine(" > RuntimeDotsStateSerializationLimits.MAX_BUFFER_ELEMENTS)")
                    .AppendLine("                    throw new FormatException(\"Invalid persisted DOTS buffer element count.\");");
                if (descriptor.PersistedBufferTailValidator != null)
                {
                    builder.Append("                var tail")
                        .Append(id)
                        .Append(" = default(")
                        .Append(TypeName(descriptor.RuntimeType))
                        .AppendLine(");");
                }
                builder.Append("                for (var index")
                    .Append(id)
                    .Append(" = 0; index")
                    .Append(id)
                    .Append(" < count")
                    .Append(id)
                    .Append("; index")
                    .Append(id)
                    .AppendLine("++)")
                    .AppendLine("                {");
                if (descriptor.PersistedBufferTailValidator != null)
                {
                    builder.Append("                    tail")
                        .Append(id)
                        .Append(" = Read_")
                        .Append(id)
                        .AppendLine("(reader);");
                }
                else
                {
                    builder.Append("                    _ = Read_")
                        .Append(id)
                        .AppendLine("(reader);");
                }
                builder.AppendLine("                }");
                if (descriptor.PersistedBufferTailValidator != null)
                {
                    EmitBufferTailValidation(
                        builder,
                        descriptor,
                        $"count{id}",
                        $"tail{id}",
                        "                ",
                        payload: true);
                }
            }
            else if (!descriptor.IsZeroSized)
            {
                builder.Append("                _ = Read_")
                    .Append(id)
                    .AppendLine("(reader);");
            }
            builder.AppendLine("            }");
        }

        private static void EmitReadEntityComponent(
            StringBuilder builder,
            RuntimeDotsStateGeneratedComponentDescriptor descriptor,
            bool prevalidateOnly)
        {
            var id = descriptor.Schema.ComponentTypeId;
            var typeName = TypeName(descriptor.RuntimeType);
            var hasMethod = descriptor.Schema.Kind ==
                            RuntimeDotsStateComponentKind.Buffer
                ? "HasBuffer"
                : "HasComponent";
            builder.AppendLine()
                .Append("            var sourcePresent")
                .Append(id)
                .AppendLine(" = reader.ReadBoolean();")
                .Append("            var targetPresent")
                .Append(id)
                .Append(" = entityManager.")
                .Append(hasMethod)
                .Append('<')
                .Append(typeName)
                .AppendLine(">(entity);")
                .Append("            if (sourcePresent")
                .Append(id)
                .Append(" != targetPresent")
                .Append(id)
                .AppendLine(")")
                .Append("                throw new InvalidOperationException(")
                .Append(Quote(
                    $"Factory topology/signature mismatch for persisted component id {id}."))
                .AppendLine(");")
                .Append("            if (sourcePresent")
                .Append(id)
                .AppendLine(")")
                .AppendLine("            {");
            if (descriptor.Schema.Enableable)
            {
                if (prevalidateOnly)
                {
                    builder.AppendLine(
                        "                _ = reader.ReadBoolean();");
                }
                else
                {
                    builder.Append("                var enabled")
                        .Append(id)
                        .AppendLine(" = reader.ReadBoolean();");
                }
            }
            if (descriptor.Schema.Kind ==
                RuntimeDotsStateComponentKind.Buffer)
            {
                builder.Append("                var count")
                    .Append(id)
                    .AppendLine(" = reader.ReadInt32();")
                    .Append("                if (count")
                    .Append(id)
                    .Append(" < 0 || count")
                    .Append(id)
                    .AppendLine(" > RuntimeDotsStateSerializationLimits.MAX_BUFFER_ELEMENTS)")
                    .Append("                    throw new FormatException(\"Invalid persisted DOTS buffer element count.\");")
                    .AppendLine();
                if (!prevalidateOnly)
                {
                    builder.Append("                var buffer")
                        .Append(id)
                        .Append(" = entityManager.GetBuffer<")
                        .Append(typeName)
                        .AppendLine(">(entity);")
                        .Append("                buffer")
                        .Append(id)
                        .AppendLine(".Clear();");
                }
                else if (descriptor.PersistedBufferTailValidator != null)
                {
                    builder.Append("                var tail")
                        .Append(id)
                        .Append(" = default(")
                        .Append(typeName)
                        .AppendLine(");");
                }
                builder.Append("                for (var index")
                    .Append(id)
                    .Append(" = 0; index")
                    .Append(id)
                    .Append(" < count")
                    .Append(id)
                    .Append("; index")
                    .Append(id)
                    .AppendLine("++)")
                    .AppendLine("                {");
                if (prevalidateOnly)
                {
                    if (descriptor.PersistedBufferTailValidator != null)
                    {
                        builder.Append("                    tail")
                            .Append(id)
                            .Append(" = Read_")
                            .Append(id)
                            .AppendLine("(reader);");
                    }
                    else
                    {
                        builder.Append("                    _ = Read_")
                            .Append(id)
                            .AppendLine("(reader);");
                    }
                }
                else
                {
                    builder.Append("                    var value")
                        .Append(id)
                        .Append(" = Read_")
                        .Append(id)
                        .AppendLine("(reader);");
                }
                if (!prevalidateOnly)
                {
                    builder.Append("                    buffer")
                        .Append(id)
                        .Append(".Add(value")
                        .Append(id)
                        .AppendLine(");");
                }
                builder.AppendLine("                }");
                if (prevalidateOnly
                    && descriptor.PersistedBufferTailValidator != null)
                {
                    EmitBufferTailValidation(
                        builder,
                        descriptor,
                        $"count{id}",
                        $"tail{id}",
                        "                ",
                        payload: true);
                }
            }
            else if (!descriptor.IsZeroSized)
            {
                if (prevalidateOnly)
                {
                    builder.Append("                _ = Read_")
                        .Append(id)
                        .AppendLine("(reader);");
                }
                else
                {
                    builder.Append("                var value")
                        .Append(id)
                        .Append(" = Read_")
                        .Append(id)
                        .AppendLine("(reader);")
                        .Append("                entityManager.SetComponentData(entity, value")
                        .Append(id)
                        .AppendLine(");");
                }
            }
            if (descriptor.Schema.Enableable && !prevalidateOnly)
            {
                builder.Append("                entityManager.SetComponentEnabled<")
                    .Append(typeName)
                    .Append(">(entity, enabled")
                    .Append(id)
                    .AppendLine(");");
            }
            builder.AppendLine("            }");
        }

        private static void EmitBufferTailValidation(
            StringBuilder builder,
            RuntimeDotsStateGeneratedComponentDescriptor descriptor,
            string countExpression,
            string tailExpression,
            string indent,
            bool payload)
        {
            var validator = descriptor.PersistedBufferTailValidator
                            ?? throw new InvalidOperationException(
                                "A generated buffer tail validator is required.");
            builder.Append(indent)
                .Append("if (")
                .Append(countExpression)
                .Append(" > 0 && !")
                .Append(TypeName(validator.DeclaringType))
                .Append(".@")
                .Append(validator.Name)
                .Append("(in ")
                .Append(tailExpression)
                .AppendLine("))")
                .Append(indent)
                .Append("    throw new ")
                .Append(payload ? "FormatException" : "InvalidOperationException")
                .Append('(')
                .Append(Quote(
                    $"Persisted DOTS buffer id {descriptor.Schema.ComponentTypeId} has a non-canonical tail."))
                .AppendLine(");");
        }

        private static void EmitPersistedCodec(
            StringBuilder builder,
            RuntimeDotsStateGeneratedComponentDescriptor descriptor)
        {
            if (descriptor.PersistedValue == null)
            {
                throw new InvalidOperationException(
                    $"Persisted DOTS state component '{descriptor.RuntimeType.FullName}' has no generated value descriptor.");
            }

            var id = descriptor.Schema.ComponentTypeId;
            var typeName = TypeName(descriptor.RuntimeType);
            builder.AppendLine()
                .Append("        public static readonly RuntimeDotsStateComponentCodec<")
                .Append(typeName)
                .Append("> Codec_")
                .Append(id)
                .Append(" = new RuntimeDotsStateComponentCodec<")
                .Append(typeName)
                .Append(">(Write_")
                .Append(id)
                .Append(", Read_")
                .Append(id)
                .AppendLine(");")
                .AppendLine()
                .Append("        public static void Write_")
                .Append(id)
                .AppendLine("(")
                .AppendLine("            RuntimeReplayCheckpointWriter writer,")
                .Append("            in ")
                .Append(typeName)
                .AppendLine(" value)")
                .AppendLine("        {")
                .AppendLine("            if (writer == null)")
                .AppendLine("                throw new ArgumentNullException(nameof(writer));");
            EmitWriteValue(
                builder,
                descriptor.PersistedValue,
                "value",
                "            ");
            builder.AppendLine("        }")
                .AppendLine()
                .Append("        public static ")
                .Append(typeName)
                .Append(" Read_")
                .Append(id)
                .AppendLine("(")
                .AppendLine("            RuntimeReplayCheckpointReader reader)")
                .AppendLine("        {")
                .AppendLine("            if (reader == null)")
                .AppendLine("                throw new ArgumentNullException(nameof(reader));")
                .Append("            var value = default(")
                .Append(typeName)
                .AppendLine(");");
            EmitReadValue(
                builder,
                descriptor.PersistedValue,
                "value",
                "            ");
            builder.AppendLine("            return value;")
                .AppendLine("        }");
        }

        private static void EmitWriteValue(
            StringBuilder builder,
            RuntimeDotsStateGeneratedValueDescriptor descriptor,
            string value,
            string indent)
        {
            if (descriptor.Kind == RuntimeDotsStateGeneratedValueKind.Struct)
            {
                for (var i = 0; i < descriptor.Fields.Count; i++)
                {
                    var field = descriptor.Fields[i];
                    EmitWriteValue(
                        builder,
                        field.ValueType,
                        $"{value}.@{field.Field.Name}",
                        indent);
                }
                return;
            }

            builder.Append(indent)
                .Append(WriteStatement(descriptor, value))
                .AppendLine();
        }

        private static void EmitReadValue(
            StringBuilder builder,
            RuntimeDotsStateGeneratedValueDescriptor descriptor,
            string target,
            string indent)
        {
            if (descriptor.Kind == RuntimeDotsStateGeneratedValueKind.Struct)
            {
                for (var i = 0; i < descriptor.Fields.Count; i++)
                {
                    var field = descriptor.Fields[i];
                    EmitReadValue(
                        builder,
                        field.ValueType,
                        $"{target}.@{field.Field.Name}",
                        indent);
                }
                return;
            }

            builder.Append(indent)
                .Append(target)
                .Append(" = ")
                .Append(ReadExpression(descriptor))
                .AppendLine(";");
        }

        private static string WriteStatement(
            RuntimeDotsStateGeneratedValueDescriptor descriptor,
            string value)
        {
            switch (descriptor.Kind)
            {
                case RuntimeDotsStateGeneratedValueKind.Boolean:
                    return $"writer.WriteBoolean({value});";
                case RuntimeDotsStateGeneratedValueKind.Byte:
                    return $"writer.WriteByte({value});";
                case RuntimeDotsStateGeneratedValueKind.SByte:
                    return $"writer.WriteByte(unchecked((byte){value}));";
                case RuntimeDotsStateGeneratedValueKind.Char:
                    return $"writer.WriteUInt32({value});";
                case RuntimeDotsStateGeneratedValueKind.Int16:
                    return $"writer.WriteInt32({value});";
                case RuntimeDotsStateGeneratedValueKind.UInt16:
                    return $"writer.WriteUInt32({value});";
                case RuntimeDotsStateGeneratedValueKind.Int32:
                    return $"writer.WriteInt32({value});";
                case RuntimeDotsStateGeneratedValueKind.UInt32:
                    return $"writer.WriteUInt32({value});";
                case RuntimeDotsStateGeneratedValueKind.Int64:
                    return $"writer.WriteInt64({value});";
                case RuntimeDotsStateGeneratedValueKind.UInt64:
                    return $"writer.WriteUInt64({value});";
                case RuntimeDotsStateGeneratedValueKind.Single:
                    return $"writer.WriteSingle({value});";
                case RuntimeDotsStateGeneratedValueKind.Double:
                    return $"writer.WriteDouble({value});";
                case RuntimeDotsStateGeneratedValueKind.FixedString32:
                    return $"writer.WriteString({value}.ToString());";
                case RuntimeDotsStateGeneratedValueKind.Enum:
                    return WriteEnumStatement(
                        descriptor.EnumUnderlyingType,
                        value);
                default:
                    throw new InvalidOperationException(
                        $"Cannot emit canonical DOTS write for {descriptor.Kind}.");
            }
        }

        private static string ReadExpression(
            RuntimeDotsStateGeneratedValueDescriptor descriptor)
        {
            switch (descriptor.Kind)
            {
                case RuntimeDotsStateGeneratedValueKind.Boolean:
                    return "reader.ReadBoolean()";
                case RuntimeDotsStateGeneratedValueKind.Byte:
                    return "reader.ReadByte()";
                case RuntimeDotsStateGeneratedValueKind.SByte:
                    return "unchecked((sbyte)reader.ReadByte())";
                case RuntimeDotsStateGeneratedValueKind.Char:
                    return "checked((char)reader.ReadUInt32())";
                case RuntimeDotsStateGeneratedValueKind.Int16:
                    return "checked((short)reader.ReadInt32())";
                case RuntimeDotsStateGeneratedValueKind.UInt16:
                    return "checked((ushort)reader.ReadUInt32())";
                case RuntimeDotsStateGeneratedValueKind.Int32:
                    return "reader.ReadInt32()";
                case RuntimeDotsStateGeneratedValueKind.UInt32:
                    return "reader.ReadUInt32()";
                case RuntimeDotsStateGeneratedValueKind.Int64:
                    return "reader.ReadInt64()";
                case RuntimeDotsStateGeneratedValueKind.UInt64:
                    return "reader.ReadUInt64()";
                case RuntimeDotsStateGeneratedValueKind.Single:
                    return "reader.ReadSingle()";
                case RuntimeDotsStateGeneratedValueKind.Double:
                    return "reader.ReadDouble()";
                case RuntimeDotsStateGeneratedValueKind.FixedString32:
                    return "new global::Unity.Collections.FixedString32Bytes(reader.ReadString(global::Unity.Collections.FixedString32Bytes.UTF8MaxLengthInBytes))";
                case RuntimeDotsStateGeneratedValueKind.Enum:
                    return $"({TypeName(descriptor.RuntimeType)})({ReadUnderlyingExpression(descriptor.EnumUnderlyingType)})";
                default:
                    throw new InvalidOperationException(
                        $"Cannot emit canonical DOTS read for {descriptor.Kind}.");
            }
        }

        private static string WriteEnumStatement(
            Type underlyingType,
            string value)
        {
            var cast = $"({TypeName(underlyingType)}){value}";
            if (underlyingType == typeof(byte))
                return $"writer.WriteByte({cast});";
            if (underlyingType == typeof(sbyte))
                return $"writer.WriteByte(unchecked((byte){cast}));";
            if (underlyingType == typeof(short))
                return $"writer.WriteInt32({cast});";
            if (underlyingType == typeof(ushort))
                return $"writer.WriteUInt32({cast});";
            if (underlyingType == typeof(int))
                return $"writer.WriteInt32({cast});";
            if (underlyingType == typeof(uint))
                return $"writer.WriteUInt32({cast});";
            if (underlyingType == typeof(long))
                return $"writer.WriteInt64({cast});";
            if (underlyingType == typeof(ulong))
                return $"writer.WriteUInt64({cast});";
            throw new InvalidOperationException(
                $"Unsupported enum underlying type '{underlyingType.FullName}'.");
        }

        private static string ReadUnderlyingExpression(Type underlyingType)
        {
            if (underlyingType == typeof(byte))
                return "reader.ReadByte()";
            if (underlyingType == typeof(sbyte))
                return "unchecked((sbyte)reader.ReadByte())";
            if (underlyingType == typeof(short))
                return "checked((short)reader.ReadInt32())";
            if (underlyingType == typeof(ushort))
                return "checked((ushort)reader.ReadUInt32())";
            if (underlyingType == typeof(int))
                return "reader.ReadInt32()";
            if (underlyingType == typeof(uint))
                return "reader.ReadUInt32()";
            if (underlyingType == typeof(long))
                return "reader.ReadInt64()";
            if (underlyingType == typeof(ulong))
                return "reader.ReadUInt64()";
            throw new InvalidOperationException(
                $"Unsupported enum underlying type '{underlyingType.FullName}'.");
        }

        private static string TypeName(Type type)
        {
            if (type == null)
            {
                throw new ArgumentNullException(nameof(type));
            }
            if (type.ContainsGenericParameters)
            {
                throw new InvalidOperationException(
                    $"Generated DOTS state type '{type}' contains generic parameters.");
            }
            if (type.IsGenericType)
            {
                var definitionName = type.GetGenericTypeDefinition().FullName;
                var tick = definitionName?.IndexOf('`') ?? -1;
                if (tick >= 0)
                {
                    definitionName = definitionName.Substring(0, tick);
                }
                var arguments = type.GetGenericArguments()
                    .Select(TypeName);
                return $"global::{definitionName?.Replace('+', '.')}<{string.Join(", ", arguments)}>";
            }

            var fullName = type.FullName;
            if (string.IsNullOrWhiteSpace(fullName))
            {
                throw new InvalidOperationException(
                    $"Generated DOTS state type '{type}' has no full name.");
            }
            return "global::" + fullName.Replace('+', '.');
        }

        private static string Quote(string value)
        {
            if (value == null)
            {
                return "null";
            }

            var builder = new StringBuilder(value.Length + 2);
            builder.Append('"');
            for (var i = 0; i < value.Length; i++)
            {
                switch (value[i])
                {
                    case '\\': builder.Append("\\\\"); break;
                    case '"': builder.Append("\\\""); break;
                    case '\r': builder.Append("\\r"); break;
                    case '\n': builder.Append("\\n"); break;
                    case '\t': builder.Append("\\t"); break;
                    default:
                        if (char.IsControl(value[i]))
                        {
                            builder.Append("\\u")
                                .Append(((int)value[i]).ToString("x4"));
                        }
                        else
                        {
                            builder.Append(value[i]);
                        }
                        break;
                }
            }
            builder.Append('"');
            return builder.ToString();
        }
    }
}
