using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DingoGameObjectsCMS.RuntimeObjects.Overrides;
using UnityEngine;

namespace DingoGameObjectsCMS.Editor
{
    public interface IRuntimePatchCodeEmissionExtension
    {
        void EmitRegistryMembers(
            RuntimePatchSourceBuilder builder,
            RuntimePatchSchemaManifest manifest,
            IReadOnlyList<RuntimePatchGeneratedComponentDescriptor> components);

        void EmitComponentMembers(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component);
    }

    public sealed class RuntimePatchCodeEmissionProfile
    {
        public string GeneratedNamespace { get; }
        public string RegistryClassName { get; }
        public IReadOnlyList<IRuntimePatchCodeEmissionExtension> Extensions { get; }

        public RuntimePatchCodeEmissionProfile(
            string generatedNamespace,
            string registryClassName,
            IReadOnlyList<IRuntimePatchCodeEmissionExtension> extensions = null)
        {
            GeneratedNamespace = RequireNamespace(generatedNamespace, nameof(generatedNamespace));
            RegistryClassName = RequireIdentifier(registryClassName, nameof(registryClassName));
            if (extensions == null)
                Extensions = Array.Empty<IRuntimePatchCodeEmissionExtension>();
            else
                Extensions = new List<IRuntimePatchCodeEmissionExtension>(extensions).AsReadOnly();

            for (var i = 0; i < Extensions.Count; i++)
            {
                if (Extensions[i] == null)
                    throw new ArgumentException("Runtime patch code emission extensions cannot contain null entries.", nameof(extensions));
            }
        }

        private static string RequireNamespace(string value, string parameterName)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new ArgumentException("Generated namespace is required.", parameterName);
            var result = value.Trim();
            var segments = result.Split('.');
            for (var i = 0; i < segments.Length; i++)
                RequireIdentifier(segments[i], parameterName);
            return result;
        }

        private static string RequireIdentifier(string value, string parameterName)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new ArgumentException("Generated C# identifier is required.", parameterName);
            var result = value.Trim();
            if (!(char.IsLetter(result[0]) || result[0] == '_'))
                throw new ArgumentException($"Generated C# identifier '{result}' is invalid.", parameterName);
            for (var i = 1; i < result.Length; i++)
            {
                if (!(char.IsLetterOrDigit(result[i]) || result[i] == '_'))
                    throw new ArgumentException($"Generated C# identifier '{result}' is invalid.", parameterName);
            }
            return result;
        }
    }

    public class RuntimePatchSourceBuilder
    {
        private readonly StringBuilder _builder = new();
        private int _indent;

        public void Line(string value = "")
        {
            if (value.Length > 0)
                _builder.Append(' ', _indent * 4).Append(value);
            _builder.Append('\n');
        }

        public void Open(string declaration)
        {
            Line(declaration);
            Line("{");
            _indent++;
        }

        public void Close(string suffix = "")
        {
            _indent--;
            Line("}" + suffix);
        }

        public override string ToString()
        {
            return _builder.ToString();
        }
    }

    public static class RuntimePatchCodeEmitter
    {
        public static string Generate(
            RuntimePatchSchemaManifest manifest,
            IReadOnlyList<RuntimePatchGeneratedComponentDescriptor> components,
            RuntimePatchCodeEmissionProfile profile)
        {
            if (manifest == null)
                throw new ArgumentNullException(nameof(manifest));
            if (components == null)
                throw new ArgumentNullException(nameof(components));
            if (profile == null)
                throw new ArgumentNullException(nameof(profile));
            if (string.IsNullOrWhiteSpace(manifest.SchemaHash))
                throw new InvalidOperationException("Generated runtime patch registry requires a schema hash.");

            var builder = new RuntimePatchSourceBuilder();
            builder.Line("// <auto-generated />");
            builder.Line("using System;");
            builder.Line("using System.Collections.Generic;");
            builder.Line("using System.Reflection;");
            builder.Line("using DingoGameObjectsCMS.RuntimeObjects.Overrides;");
            builder.Line();
            builder.Open($"namespace {profile.GeneratedNamespace}");
            EmitRegistry(builder, manifest, components, profile);
            for (var i = 0; i < components.Count; i++)
            {
                builder.Line();
                EmitComponentCodec(builder, components[i], profile);
            }
            builder.Close();
            return builder.ToString();
        }

        private static void EmitRegistry(
            RuntimePatchSourceBuilder builder,
            RuntimePatchSchemaManifest manifest,
            IReadOnlyList<RuntimePatchGeneratedComponentDescriptor> components,
            RuntimePatchCodeEmissionProfile profile)
        {
            builder.Open($"public static class {profile.RegistryClassName}");
            builder.Line($"public const string SCHEMA_HASH = {Quote(manifest.SchemaHash)};");
            builder.Line();
            EmitCreateManifest(builder, manifest);
            builder.Line();
            builder.Open("public static RuntimePatchCodecRegistry CreateRegistry()");
            builder.Line("var registry = new RuntimePatchCodecRegistry(SCHEMA_HASH);");
            builder.Line("Register(registry);");
            builder.Line("return registry;");
            builder.Close();
            builder.Line();
            builder.Open("public static void Register(RuntimePatchCodecRegistry registry)");
            builder.Line("if (registry == null)");
            builder.Line("    throw new ArgumentNullException(nameof(registry));");
            builder.Line("if (!string.Equals(registry.SchemaHash, SCHEMA_HASH, StringComparison.Ordinal))");
            builder.Line("    throw new InvalidOperationException($\"Runtime patch registry schema '{registry.SchemaHash}' does not match generated schema '{SCHEMA_HASH}'.\");");
            for (var i = 0; i < components.Count; i++)
            {
                builder.Line($"registry.Register(new {CodecClassName(components[i])}());");
            }
            builder.Close();
            for (var i = 0; i < profile.Extensions.Count; i++)
            {
                builder.Line();
                profile.Extensions[i].EmitRegistryMembers(builder, manifest, components);
            }
            builder.Close();
        }

        private static void EmitCreateManifest(
            RuntimePatchSourceBuilder builder,
            RuntimePatchSchemaManifest manifest)
        {
            builder.Open("public static RuntimePatchSchemaManifest CreateManifest()");
            builder.Line("return new RuntimePatchSchemaManifest");
            builder.Line("{");
            builder.Line($"    FormatVersion = {manifest.FormatVersion},");
            builder.Line($"    CodecVersion = {manifest.CodecVersion},");
            builder.Line($"    ComponentRegistryHash = {Quote(manifest.ComponentRegistryHash)},");
            builder.Line("    SchemaHash = SCHEMA_HASH,");
            builder.Line("    Components = new List<RuntimePatchComponentSchema>");
            builder.Line("    {");
            foreach (var component in manifest.Components
                         .Where(value => value != null)
                         .OrderBy(value => value.ComponentTypeId))
            {
                if (component.RuntimeType == null)
                {
                    throw new InvalidOperationException(
                        $"Runtime patch component {component.ComponentTypeId} requires RuntimeType = typeof(T).");
                }
                builder.Line("        new RuntimePatchComponentSchema");
                builder.Line("        {");
                builder.Line($"            ComponentTypeId = {component.ComponentTypeId},");
                builder.Line($"            RuntimeType = typeof({TypeName(component.RuntimeType)}),");
                builder.Line("            Fields = new List<RuntimePatchFieldSchema>");
                builder.Line("            {");
                foreach (var field in (component.Fields
                             ?? new List<RuntimePatchFieldSchema>())
                         .Where(value => value != null)
                         .OrderBy(value => value.FieldId))
                {
                    builder.Line("                new RuntimePatchFieldSchema");
                    builder.Line("                {");
                    builder.Line($"                    FieldId = {field.FieldId},");
                    builder.Line($"                    Encoding = RuntimePatchFieldEncoding.{field.Encoding},");
                    builder.Line("                },");
                }
                builder.Line("            },");
                builder.Line("        },");
            }
            builder.Line("    },");
            builder.Line("};");
            builder.Close();
        }

        private static void EmitComponentCodec(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            RuntimePatchCodeEmissionProfile profile)
        {
            if (component?.Schema == null || component.RuntimeType == null)
                throw new InvalidOperationException("Generated runtime patch component descriptor is incomplete.");
            var componentType = TypeName(component.RuntimeType);
            builder.Open($"public class {CodecClassName(component)} : RuntimeComponentPatchCodec<{componentType}>");
            for (var i = 0; i < component.Fields.Count; i++)
            {
                var field = component.Fields[i];
                builder.Line($"public const uint {FieldIdConstant(field)} = {field.Schema.FieldId}u;");
            }
            if (component.Fields.Count > 0)
                builder.Line();
            builder.Open($"public {CodecClassName(component)}() : base({component.Schema.ComponentTypeId}u)");
            builder.Close();
            builder.Line();
            EmitFieldInfoLookup(builder, component, componentType);
            builder.Line();
            EmitClone(builder, component, componentType);
            builder.Line();
            EmitCanonicalWrite(builder, component, componentType);
            builder.Line();
            EmitCanonicalRead(builder, component, componentType);
            builder.Line();
            EmitDiff(builder, component, componentType);
            builder.Line();
            EmitApplyField(builder, component, componentType);
            if (component.UsesCustomCodec)
            {
                builder.Line();
                EmitCustomCodec(builder, component, componentType);
            }
            for (var i = 0; i < component.Fields.Count; i++)
            {
                builder.Line();
                EmitFieldHelpers(builder, component.Fields[i]);
            }
            for (var i = 0; i < profile.Extensions.Count; i++)
            {
                builder.Line();
                profile.Extensions[i].EmitComponentMembers(builder, component);
            }
            builder.Close();
        }

        private static void EmitFieldInfoLookup(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            string componentType)
        {
            builder.Line($"public override uint FieldCount => {component.Fields.Count}u;");
            builder.Line();
            builder.Open("public override bool TryGetFieldInfo(uint fieldId, out FieldInfo field)");
            if (component.Fields.Count == 0)
            {
                builder.Line("field = null;");
                builder.Line("return false;");
                builder.Close();
                return;
            }

            builder.Open("switch (fieldId)");
            for (var i = 0; i < component.Fields.Count; i++)
            {
                var field = component.Fields[i];
                builder.Line($"case {FieldIdConstant(field)}:");
                builder.Line($"    field = typeof({componentType}).GetField(nameof({componentType}.{FieldAccess(field.Field.Name)}));");
                builder.Line("    return true;");
            }
            builder.Line("default:");
            builder.Line("    field = null;");
            builder.Line("    return false;");
            builder.Close();
            builder.Close();
        }

        private static void EmitClone(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            string componentType)
        {
            builder.Open($"protected override {componentType} CloneTyped({componentType} value)");
            builder.Line($"var result = new {componentType}();");
            for (var i = 0; i < component.Fields.Count; i++)
            {
                var field = component.Fields[i];
                builder.Line($"result.{FieldAccess(field.Field.Name)} = CloneField_{field.Schema.FieldId}(value.{FieldAccess(field.Field.Name)});");
            }
            builder.Line("return result;");
            builder.Close();
        }

        private static void EmitCanonicalWrite(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            string componentType)
        {
            builder.Open(
                $"protected override void WriteCanonicalTyped(CanonicalPatchBinaryWriter writer, {componentType} value, RuntimePatchCodecContext context)");
            for (var i = 0; i < component.Fields.Count; i++)
            {
                var field = component.Fields[i];
                builder.Line($"WriteField_{field.Schema.FieldId}(writer, value.{FieldAccess(field.Field.Name)}, context);");
            }
            builder.Close();
        }

        private static void EmitCanonicalRead(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            string componentType)
        {
            builder.Open(
                $"protected override {componentType} ReadCanonicalTyped(CanonicalPatchBinaryReader reader, RuntimePatchCodecContext context)");
            builder.Line($"var result = new {componentType}();");
            for (var i = 0; i < component.Fields.Count; i++)
            {
                var field = component.Fields[i];
                builder.Line($"result.{FieldAccess(field.Field.Name)} = ReadField_{field.Schema.FieldId}(reader, context);");
            }
            builder.Line("return result;");
            builder.Close();
        }

        private static void EmitDiff(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            string componentType)
        {
            builder.Open(
                $"protected override void CollectFieldPatchesTyped({componentType} baseline, {componentType} current, List<FieldPatch> fields, RuntimePatchCodecContext context)");
            if (!component.UsesCustomCodec)
            {
                for (var i = 0; i < component.Fields.Count; i++)
                {
                    var field = component.Fields[i];
                    builder.Line($"if (!AreField_{field.Schema.FieldId}Equal(baseline.{FieldAccess(field.Field.Name)}, current.{FieldAccess(field.Field.Name)}, context))");
                    builder.Line($"    fields.Add(new FieldPatch({FieldIdConstant(field)}, FieldPatchKind.Set, EncodeField_{field.Schema.FieldId}(current.{FieldAccess(field.Field.Name)}, context)));");
                }
            }
            builder.Close();
        }

        private static void EmitApplyField(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            string componentType)
        {
            builder.Open(
                $"protected override void ApplyFieldPatchTyped({componentType} target, FieldPatch fieldPatch, RuntimePatchCodecContext context)");
            if (component.UsesCustomCodec || component.Fields.Count == 0)
            {
                builder.Line($"throw new InvalidOperationException($\"Component {component.Schema.ComponentTypeId} has no field patch '{{fieldPatch.FieldId}}'.\");");
                builder.Close();
                return;
            }
            builder.Open("switch (fieldPatch.FieldId)");
            for (var i = 0; i < component.Fields.Count; i++)
            {
                var field = component.Fields[i];
                builder.Line($"case {FieldIdConstant(field)}:");
                builder.Line($"    target.{FieldAccess(field.Field.Name)} = fieldPatch.Kind == FieldPatchKind.Remove");
                builder.Line($"        ? default({TypeName(field.Field.FieldType)})");
                builder.Line($"        : DecodeField_{field.Schema.FieldId}(fieldPatch.Payload, context);");
                builder.Line("    return;");
            }
            builder.Line("default:");
            builder.Line("    throw new InvalidOperationException($\"Unknown runtime patch field id {fieldPatch.FieldId}.\");");
            builder.Close();
            builder.Close();
        }

        private static void EmitCustomCodec(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedComponentDescriptor component,
            string componentType)
        {
            builder.Open(
                $"protected override bool TryBuildCustomPatchTyped({componentType} baseline, {componentType} current, RuntimePatchCodecContext context, out byte[] payload)");
            var equalParts = new List<string>();
            for (var i = 0; i < component.Fields.Count; i++)
            {
                var field = component.Fields[i];
                equalParts.Add($"AreField_{field.Schema.FieldId}Equal(baseline.{FieldAccess(field.Field.Name)}, current.{FieldAccess(field.Field.Name)}, context)");
            }
            var equalExpression = equalParts.Count == 0 ? "true" : string.Join(" && ", equalParts);
            builder.Line($"if ({equalExpression})");
            builder.Open("");
            builder.Line("payload = null;");
            builder.Line("return false;");
            builder.Close();
            builder.Line("var writer = new CanonicalPatchBinaryWriter();");
            builder.Line("WriteCanonicalTyped(writer, current, context);");
            builder.Line("payload = writer.ToArray();");
            builder.Line("return true;");
            builder.Close();
            builder.Line();
            builder.Open(
                $"protected override {componentType} ApplyCustomPatchTyped({componentType} baseline, byte[] payload, RuntimePatchCodecContext context)");
            builder.Line("var reader = new CanonicalPatchBinaryReader(payload);");
            builder.Line("var result = ReadCanonicalTyped(reader, context);");
            builder.Line("reader.RequireEnd();");
            builder.Line("return result;");
            builder.Close();
        }

        private static void EmitFieldHelpers(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedFieldDescriptor field)
        {
            var id = field.Schema.FieldId;
            var fieldType = TypeName(field.Field.FieldType);
            builder.Open(
                $"private static void WriteField_{id}(CanonicalPatchBinaryWriter writer, {fieldType} value, RuntimePatchCodecContext context)");
            var loopIndex = 0;
            EmitWriteValue(builder, field.ValueType, "value", ref loopIndex);
            builder.Close();
            builder.Line();
            builder.Open(
                $"private static {fieldType} ReadField_{id}(CanonicalPatchBinaryReader reader, RuntimePatchCodecContext context)");
            builder.Line($"var value = default({fieldType});");
            var readIndex = 0;
            EmitReadAssignments(builder, field.ValueType, "value", ref readIndex);
            builder.Line("return value;");
            builder.Close();
            builder.Line();
            builder.Open(
                $"private static bool AreField_{id}Equal({fieldType} first, {fieldType} second, RuntimePatchCodecContext context)");
            var equalityIndex = 0;
            EmitEqualityChecks(builder, field.ValueType, "first", "second", ref equalityIndex);
            builder.Line("return true;");
            builder.Close();
            builder.Line();
            builder.Open($"private static {fieldType} CloneField_{id}({fieldType} value)");
            builder.Line($"var result = default({fieldType});");
            var cloneIndex = 0;
            EmitCloneAssignments(builder, field.ValueType, "result", "value", ref cloneIndex);
            builder.Line("return result;");
            builder.Close();
            builder.Line();
            builder.Open(
                $"private static byte[] EncodeField_{id}({fieldType} value, RuntimePatchCodecContext context)");
            builder.Line("var writer = new CanonicalPatchBinaryWriter();");
            builder.Line($"WriteField_{id}(writer, value, context);");
            builder.Line("return writer.ToArray();");
            builder.Close();
            builder.Line();
            builder.Open(
                $"private static {fieldType} DecodeField_{id}(byte[] payload, RuntimePatchCodecContext context)");
            builder.Line("var reader = new CanonicalPatchBinaryReader(payload);");
            builder.Line($"var value = ReadField_{id}(reader, context);");
            builder.Line("reader.RequireEnd();");
            builder.Line("return value;");
            builder.Close();
        }

        private static void EmitWriteValue(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedTypeDescriptor descriptor,
            string value,
            ref int loopIndex)
        {
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.Struct)
            {
                for (var i = 0; i < descriptor.Members.Count; i++)
                {
                    var member = descriptor.Members[i];
                    EmitWriteValue(builder, member.ValueType, $"{value}.{FieldAccess(member.Field.Name)}", ref loopIndex);
                }
                return;
            }
            if (IsList(descriptor))
            {
                var index = loopIndex++;
                var elementType = ListElementType(descriptor);
                builder.Line($"if ({value} == null)");
                builder.Line("    writer.WriteInt32(-1);");
                builder.Line("else");
                builder.Open("");
                builder.Line($"RuntimePatchGeneratedValueCodec.RequireCollectionCountForWrite({value}.Count);");
                builder.Line($"writer.WriteInt32({value}.Count);");
                builder.Open($"for (var itemIndex{index} = 0; itemIndex{index} < {value}.Count; itemIndex{index}++)");
                EmitWriteValue(builder, elementType, $"{value}[itemIndex{index}]", ref loopIndex);
                builder.Close();
                builder.Close();
                return;
            }
            builder.Line(WriteStatement(descriptor, value));
        }

        private static void EmitReadAssignments(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedTypeDescriptor descriptor,
            string target,
            ref int temporaryIndex)
        {
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.Struct)
            {
                for (var i = 0; i < descriptor.Members.Count; i++)
                {
                    var member = descriptor.Members[i];
                    EmitReadAssignments(builder, member.ValueType, $"{target}.{FieldAccess(member.Field.Name)}", ref temporaryIndex);
                }
                return;
            }
            if (IsList(descriptor))
            {
                var index = temporaryIndex++;
                var elementType = ListElementType(descriptor);
                builder.Line($"var count{index} = RuntimePatchGeneratedValueCodec.ReadCollectionCount(reader);");
                builder.Line($"if (count{index} < 0)");
                builder.Line($"    {target} = null;");
                builder.Line("else");
                builder.Open("");
                builder.Line($"var list{index} = new {TypeName(descriptor.RuntimeType)}(count{index});");
                builder.Open($"for (var itemIndex{index} = 0; itemIndex{index} < count{index}; itemIndex{index}++)");
                builder.Line($"var item{index} = default({TypeName(elementType.RuntimeType)});");
                EmitReadAssignments(builder, elementType, $"item{index}", ref temporaryIndex);
                builder.Line($"list{index}.Add(item{index});");
                builder.Close();
                builder.Line($"{target} = list{index};");
                builder.Close();
                return;
            }
            builder.Line($"{target} = {ReadExpression(descriptor)};");
        }

        private static void EmitCloneAssignments(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedTypeDescriptor descriptor,
            string target,
            string source,
            ref int temporaryIndex)
        {
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.Struct)
            {
                for (var i = 0; i < descriptor.Members.Count; i++)
                {
                    var member = descriptor.Members[i];
                    EmitCloneAssignments(
                        builder,
                        member.ValueType,
                        $"{target}.{FieldAccess(member.Field.Name)}",
                        $"{source}.{FieldAccess(member.Field.Name)}",
                        ref temporaryIndex);
                }
                return;
            }
            if (IsList(descriptor))
            {
                var index = temporaryIndex++;
                var elementType = ListElementType(descriptor);
                builder.Line($"if ({source} == null)");
                builder.Line($"    {target} = null;");
                builder.Line("else");
                builder.Open("");
                builder.Line($"var list{index} = new {TypeName(descriptor.RuntimeType)}({source}.Count);");
                builder.Open($"for (var itemIndex{index} = 0; itemIndex{index} < {source}.Count; itemIndex{index}++)");
                builder.Line($"var item{index} = default({TypeName(elementType.RuntimeType)});");
                EmitCloneAssignments(
                    builder,
                    elementType,
                    $"item{index}",
                    $"{source}[itemIndex{index}]",
                    ref temporaryIndex);
                builder.Line($"list{index}.Add(item{index});");
                builder.Close();
                builder.Line($"{target} = list{index};");
                builder.Close();
                return;
            }
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.RuntimeObjectPatch)
            {
                builder.Line($"{target} = RuntimePatchGeneratedValueCodec.CloneRuntimeObjectPatch({source});");
                return;
            }
            builder.Line($"{target} = {source};");
        }

        private static void EmitEqualityChecks(
            RuntimePatchSourceBuilder builder,
            RuntimePatchGeneratedTypeDescriptor descriptor,
            string first,
            string second,
            ref int temporaryIndex)
        {
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.Struct)
            {
                for (var i = 0; i < descriptor.Members.Count; i++)
                {
                    var member = descriptor.Members[i];
                    EmitEqualityChecks(
                        builder,
                        member.ValueType,
                        $"{first}.{FieldAccess(member.Field.Name)}",
                        $"{second}.{FieldAccess(member.Field.Name)}",
                        ref temporaryIndex);
                }
                return;
            }
            if (IsList(descriptor))
            {
                var index = temporaryIndex++;
                var elementType = ListElementType(descriptor);
                builder.Open($"if (!ReferenceEquals({first}, {second}))");
                builder.Line($"if ({first} == null || {second} == null || {first}.Count != {second}.Count)");
                builder.Line("    return false;");
                builder.Open($"for (var itemIndex{index} = 0; itemIndex{index} < {first}.Count; itemIndex{index}++)");
                EmitEqualityChecks(
                    builder,
                    elementType,
                    $"{first}[itemIndex{index}]",
                    $"{second}[itemIndex{index}]",
                    ref temporaryIndex);
                builder.Close();
                builder.Close();
                return;
            }

            string equalExpression;
            switch (descriptor.Kind)
            {
                case RuntimePatchGeneratedValueKind.String:
                    equalExpression = $"string.Equals({first}, {second}, StringComparison.Ordinal)";
                    break;
                case RuntimePatchGeneratedValueKind.Single:
                case RuntimePatchGeneratedValueKind.Double:
                case RuntimePatchGeneratedValueKind.Int2:
                case RuntimePatchGeneratedValueKind.Float2:
                case RuntimePatchGeneratedValueKind.Vector2Int:
                case RuntimePatchGeneratedValueKind.Hash128:
                    equalExpression = $"{first}.Equals({second})";
                    break;
                case RuntimePatchGeneratedValueKind.RuntimeInstance:
                    equalExpression = $"context.RuntimeInstancesEqual({first}, {second})";
                    break;
                case RuntimePatchGeneratedValueKind.RuntimeObjectPatch:
                    equalExpression =
                        $"RuntimePatchGeneratedValueCodec.RuntimeObjectPatchesEqual({first}, {second})";
                    break;
                default:
                    equalExpression = $"{first} == {second}";
                    break;
            }
            builder.Line($"if (!({equalExpression}))");
            builder.Line("    return false;");
        }

        private static bool IsList(RuntimePatchGeneratedTypeDescriptor descriptor)
        {
            return descriptor.Kind == RuntimePatchGeneratedValueKind.List
                   || descriptor.Kind == RuntimePatchGeneratedValueKind.ListVector2Int;
        }

        private static RuntimePatchGeneratedTypeDescriptor ListElementType(
            RuntimePatchGeneratedTypeDescriptor descriptor)
        {
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.List)
            {
                return descriptor.ElementType
                       ?? throw new InvalidOperationException(
                           $"Generated list descriptor '{descriptor.RuntimeType}' has no element type.");
            }
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.ListVector2Int)
            {
                return new RuntimePatchGeneratedTypeDescriptor
                {
                    RuntimeType = typeof(Vector2Int),
                    Kind = RuntimePatchGeneratedValueKind.Vector2Int,
                };
            }
            throw new InvalidOperationException($"Generated patch value '{descriptor.Kind}' is not a list.");
        }

        private static string WriteStatement(RuntimePatchGeneratedTypeDescriptor descriptor, string value)
        {
            switch (descriptor.Kind)
            {
                case RuntimePatchGeneratedValueKind.Boolean: return $"writer.WriteBoolean({value});";
                case RuntimePatchGeneratedValueKind.Byte: return $"writer.WriteByte({value});";
                case RuntimePatchGeneratedValueKind.SByte: return $"writer.WriteByte(unchecked((byte){value}));";
                case RuntimePatchGeneratedValueKind.Int16: return $"writer.WriteInt32({value});";
                case RuntimePatchGeneratedValueKind.UInt16: return $"writer.WriteUInt32({value});";
                case RuntimePatchGeneratedValueKind.Int32: return $"writer.WriteInt32({value});";
                case RuntimePatchGeneratedValueKind.UInt32: return $"writer.WriteUInt32({value});";
                case RuntimePatchGeneratedValueKind.Int64: return $"writer.WriteInt64({value});";
                case RuntimePatchGeneratedValueKind.UInt64: return $"writer.WriteUInt64({value});";
                case RuntimePatchGeneratedValueKind.Single: return $"writer.WriteSingle({value});";
                case RuntimePatchGeneratedValueKind.Double: return $"writer.WriteDouble({value});";
                case RuntimePatchGeneratedValueKind.String: return $"writer.WriteString({value});";
                case RuntimePatchGeneratedValueKind.Int2:
                    return $"writer.WriteInt32({value}.x); writer.WriteInt32({value}.y);";
                case RuntimePatchGeneratedValueKind.Float2:
                    return $"writer.WriteSingle({value}.x); writer.WriteSingle({value}.y);";
                case RuntimePatchGeneratedValueKind.Vector2Int:
                    return $"writer.WriteInt32({value}.x); writer.WriteInt32({value}.y);";
                case RuntimePatchGeneratedValueKind.RuntimeInstance:
                    return $"context.WriteRuntimeInstance(writer, {value});";
                case RuntimePatchGeneratedValueKind.Hash128:
                    return $"writer.WriteHash128({value});";
                case RuntimePatchGeneratedValueKind.RuntimeObjectPatch:
                    return $"RuntimePatchGeneratedValueCodec.WriteRuntimeObjectPatch(writer, {value});";
                case RuntimePatchGeneratedValueKind.Enum:
                    return WriteEnumStatement(descriptor.EnumUnderlyingType, value);
                default:
                    throw new InvalidOperationException($"Cannot emit scalar write for {descriptor.Kind}.");
            }
        }

        private static string ReadExpression(RuntimePatchGeneratedTypeDescriptor descriptor)
        {
            switch (descriptor.Kind)
            {
                case RuntimePatchGeneratedValueKind.Boolean: return "reader.ReadBoolean()";
                case RuntimePatchGeneratedValueKind.Byte: return "reader.ReadByte()";
                case RuntimePatchGeneratedValueKind.SByte: return "unchecked((sbyte)reader.ReadByte())";
                case RuntimePatchGeneratedValueKind.Int16: return "checked((short)reader.ReadInt32())";
                case RuntimePatchGeneratedValueKind.UInt16: return "checked((ushort)reader.ReadUInt32())";
                case RuntimePatchGeneratedValueKind.Int32: return "reader.ReadInt32()";
                case RuntimePatchGeneratedValueKind.UInt32: return "reader.ReadUInt32()";
                case RuntimePatchGeneratedValueKind.Int64: return "reader.ReadInt64()";
                case RuntimePatchGeneratedValueKind.UInt64: return "reader.ReadUInt64()";
                case RuntimePatchGeneratedValueKind.Single: return "reader.ReadSingle()";
                case RuntimePatchGeneratedValueKind.Double: return "reader.ReadDouble()";
                case RuntimePatchGeneratedValueKind.String: return "reader.ReadString()";
                case RuntimePatchGeneratedValueKind.Int2:
                    return "new global::Unity.Mathematics.int2(reader.ReadInt32(), reader.ReadInt32())";
                case RuntimePatchGeneratedValueKind.Float2:
                    return "new global::Unity.Mathematics.float2(reader.ReadSingle(), reader.ReadSingle())";
                case RuntimePatchGeneratedValueKind.Vector2Int:
                    return "new global::UnityEngine.Vector2Int(reader.ReadInt32(), reader.ReadInt32())";
                case RuntimePatchGeneratedValueKind.RuntimeInstance:
                    return "context.ReadRuntimeInstance(reader)";
                case RuntimePatchGeneratedValueKind.Hash128:
                    return "RuntimePatchGeneratedValueCodec.ReadHash128(reader)";
                case RuntimePatchGeneratedValueKind.RuntimeObjectPatch:
                    return "RuntimePatchGeneratedValueCodec.ReadRuntimeObjectPatch(reader)";
                case RuntimePatchGeneratedValueKind.Enum:
                    return $"({TypeName(descriptor.RuntimeType)})({ReadUnderlyingExpression(descriptor.EnumUnderlyingType)})";
                default:
                    throw new InvalidOperationException($"Cannot emit scalar read for {descriptor.Kind}.");
            }
        }

        private static string EqualityExpression(
            RuntimePatchGeneratedTypeDescriptor descriptor,
            string first,
            string second)
        {
            if (descriptor.Kind == RuntimePatchGeneratedValueKind.Struct)
            {
                var parts = new List<string>();
                for (var i = 0; i < descriptor.Members.Count; i++)
                {
                    var member = descriptor.Members[i];
                    parts.Add(EqualityExpression(
                        member.ValueType,
                        $"{first}.{FieldAccess(member.Field.Name)}",
                        $"{second}.{FieldAccess(member.Field.Name)}"));
                }
                return parts.Count == 0 ? "true" : $"({string.Join(" && ", parts)})";
            }
            switch (descriptor.Kind)
            {
                case RuntimePatchGeneratedValueKind.String:
                    return $"string.Equals({first}, {second}, StringComparison.Ordinal)";
                case RuntimePatchGeneratedValueKind.Single:
                case RuntimePatchGeneratedValueKind.Double:
                case RuntimePatchGeneratedValueKind.Int2:
                case RuntimePatchGeneratedValueKind.Float2:
                case RuntimePatchGeneratedValueKind.Vector2Int:
                case RuntimePatchGeneratedValueKind.Hash128:
                    return $"{first}.Equals({second})";
                case RuntimePatchGeneratedValueKind.RuntimeInstance:
                    return $"context.RuntimeInstancesEqual({first}, {second})";
                case RuntimePatchGeneratedValueKind.RuntimeObjectPatch:
                    return $"RuntimePatchGeneratedValueCodec.RuntimeObjectPatchesEqual({first}, {second})";
                case RuntimePatchGeneratedValueKind.ListVector2Int:
                case RuntimePatchGeneratedValueKind.List:
                    throw new InvalidOperationException("List equality requires an explicit generated loop.");
                default:
                    return $"{first} == {second}";
            }
        }

        private static string WriteEnumStatement(Type underlyingType, string value)
        {
            var cast = $"({TypeName(underlyingType)}){value}";
            if (underlyingType == typeof(byte)) return $"writer.WriteByte({cast});";
            if (underlyingType == typeof(sbyte)) return $"writer.WriteByte(unchecked((byte){cast}));";
            if (underlyingType == typeof(short)) return $"writer.WriteInt32({cast});";
            if (underlyingType == typeof(ushort)) return $"writer.WriteUInt32({cast});";
            if (underlyingType == typeof(int)) return $"writer.WriteInt32({cast});";
            if (underlyingType == typeof(uint)) return $"writer.WriteUInt32({cast});";
            if (underlyingType == typeof(long)) return $"writer.WriteInt64({cast});";
            if (underlyingType == typeof(ulong)) return $"writer.WriteUInt64({cast});";
            throw new InvalidOperationException($"Unsupported enum underlying type '{underlyingType.FullName}'.");
        }

        private static string ReadUnderlyingExpression(Type underlyingType)
        {
            if (underlyingType == typeof(byte)) return "reader.ReadByte()";
            if (underlyingType == typeof(sbyte)) return "unchecked((sbyte)reader.ReadByte())";
            if (underlyingType == typeof(short)) return "checked((short)reader.ReadInt32())";
            if (underlyingType == typeof(ushort)) return "checked((ushort)reader.ReadUInt32())";
            if (underlyingType == typeof(int)) return "reader.ReadInt32()";
            if (underlyingType == typeof(uint)) return "reader.ReadUInt32()";
            if (underlyingType == typeof(long)) return "reader.ReadInt64()";
            if (underlyingType == typeof(ulong)) return "reader.ReadUInt64()";
            throw new InvalidOperationException($"Unsupported enum underlying type '{underlyingType.FullName}'.");
        }

        private static string TypeName(Type type)
        {
            if (type == null)
                throw new ArgumentNullException(nameof(type));
            if (type == typeof(List<Vector2Int>))
                return "global::System.Collections.Generic.List<global::UnityEngine.Vector2Int>";
            if (type.IsGenericType)
            {
                var definition = type.GetGenericTypeDefinition();
                var definitionName = definition.FullName;
                if (string.IsNullOrWhiteSpace(definitionName))
                    throw new InvalidOperationException($"Runtime patch generic type '{type}' has no full name.");
                var tick = definitionName.IndexOf('`');
                if (tick >= 0)
                    definitionName = definitionName.Substring(0, tick);
                var arguments = type.GetGenericArguments();
                var argumentNames = new string[arguments.Length];
                for (var i = 0; i < arguments.Length; i++)
                    argumentNames[i] = TypeName(arguments[i]);
                return $"global::{definitionName.Replace('+', '.')}<{string.Join(", ", argumentNames)}>";
            }
            var name = type.FullName;
            if (string.IsNullOrWhiteSpace(name))
                throw new InvalidOperationException($"Runtime patch type '{type}' has no full name.");
            return "global::" + name.Replace('+', '.');
        }

        private static string CodecClassName(RuntimePatchGeneratedComponentDescriptor component)
        {
            return $"RuntimePatchCodec_{component.Schema.ComponentTypeId}";
        }

        private static string FieldIdConstant(RuntimePatchGeneratedFieldDescriptor field)
        {
            return $"FIELD_{field.Schema.FieldId}_ID";
        }

        private static string FieldAccess(string fieldName)
        {
            return "@" + fieldName;
        }

        private static string Quote(string value)
        {
            if (value == null)
                return "null";
            var builder = new StringBuilder(value.Length + 2);
            builder.Append('"');
            for (var i = 0; i < value.Length; i++)
            {
                switch (value[i])
                {
                    case '\\': builder.Append("\\\\"); break;
                    case '"': builder.Append("\\\""); break;
                    case '\r': builder.Append("\\r"); break;
                    case '\n': builder.Append("\\n"); break;
                    case '\t': builder.Append("\\t"); break;
                    default:
                        if (char.IsControl(value[i]))
                            builder.Append("\\u").Append(((int)value[i]).ToString("x4"));
                        else
                            builder.Append(value[i]);
                        break;
                }
            }
            builder.Append('"');
            return builder.ToString();
        }

    }
}
